package Entity;
// Generated Aug 17, 2017 7:16:05 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Monhoc generated by hbm2java
 */
public class Monhoc  implements java.io.Serializable {


     private String maMonHoc;
     private String tenMonHoc;
     private Date ngayBd;
     private String thuTrongTuan;
     private Date gioBd;
     private Date gioKt;
     private String tenPhongHoc;
     private Set<Sinhvienmonhoc> sinhvienmonhocs = new HashSet<Sinhvienmonhoc>(0);

    public Monhoc() {
    }

	
    public Monhoc(String maMonHoc) {
        this.maMonHoc = maMonHoc;
    }
    public Monhoc(String maMonHoc, String tenMonHoc, Date ngayBd, String thuTrongTuan, Date gioBd, Date gioKt, String tenPhongHoc, Set<Sinhvienmonhoc> sinhvienmonhocs) {
       this.maMonHoc = maMonHoc;
       this.tenMonHoc = tenMonHoc;
       this.ngayBd = ngayBd;
       this.thuTrongTuan = thuTrongTuan;
       this.gioBd = gioBd;
       this.gioKt = gioKt;
       this.tenPhongHoc = tenPhongHoc;
       this.sinhvienmonhocs = sinhvienmonhocs;
    }
   
    public String getMaMonHoc() {
        return this.maMonHoc;
    }
    
    public void setMaMonHoc(String maMonHoc) {
        this.maMonHoc = maMonHoc;
    }
    public String getTenMonHoc() {
        return this.tenMonHoc;
    }
    
    public void setTenMonHoc(String tenMonHoc) {
        this.tenMonHoc = tenMonHoc;
    }
    public Date getNgayBd() {
        return this.ngayBd;
    }
    
    public void setNgayBd(Date ngayBd) {
        this.ngayBd = ngayBd;
    }
    public String getThuTrongTuan() {
        return this.thuTrongTuan;
    }
    
    public void setThuTrongTuan(String thuTrongTuan) {
        this.thuTrongTuan = thuTrongTuan;
    }
    public Date getGioBd() {
        return this.gioBd;
    }
    
    public void setGioBd(Date gioBd) {
        this.gioBd = gioBd;
    }
    public Date getGioKt() {
        return this.gioKt;
    }
    
    public void setGioKt(Date gioKt) {
        this.gioKt = gioKt;
    }
    public String getTenPhongHoc() {
        return this.tenPhongHoc;
    }
    
    public void setTenPhongHoc(String tenPhongHoc) {
        this.tenPhongHoc = tenPhongHoc;
    }
    public Set<Sinhvienmonhoc> getSinhvienmonhocs() {
        return this.sinhvienmonhocs;
    }
    
    public void setSinhvienmonhocs(Set<Sinhvienmonhoc> sinhvienmonhocs) {
        this.sinhvienmonhocs = sinhvienmonhocs;
    }




}


