package Entity;
// Generated Aug 17, 2017 7:16:05 AM by Hibernate Tools 4.3.1



/**
 * Sinhvienmonhoc generated by hbm2java
 */
public class Sinhvienmonhoc  implements java.io.Serializable {


     private SinhvienmonhocId id;
     private Monhoc monhoc;
     private Nguoidung nguoidung;
     private Boolean tuan1;
     private Boolean tuan2;
     private Boolean tuan3;
     private Boolean tuan4;
     private Boolean tuan5;
     private Boolean tuan6;
     private Boolean tuan7;
     private Boolean tuan8;
     private Boolean tuan9;
     private Boolean tuan10;
     private Boolean tuan11;
     private Boolean tuan12;
     private Boolean tuan13;
     private Boolean tuan14;
     private Boolean tuan15;

    public Sinhvienmonhoc() {
    }

	
    public Sinhvienmonhoc(SinhvienmonhocId id, Monhoc monhoc, Nguoidung nguoidung) {
        this.id = id;
        this.monhoc = monhoc;
        this.nguoidung = nguoidung;
    }
    public Sinhvienmonhoc(SinhvienmonhocId id, Monhoc monhoc, Nguoidung nguoidung, Boolean tuan1, Boolean tuan2, Boolean tuan3, Boolean tuan4, Boolean tuan5, Boolean tuan6, Boolean tuan7, Boolean tuan8, Boolean tuan9, Boolean tuan10, Boolean tuan11, Boolean tuan12, Boolean tuan13, Boolean tuan14, Boolean tuan15) {
       this.id = id;
       this.monhoc = monhoc;
       this.nguoidung = nguoidung;
       this.tuan1 = tuan1;
       this.tuan2 = tuan2;
       this.tuan3 = tuan3;
       this.tuan4 = tuan4;
       this.tuan5 = tuan5;
       this.tuan6 = tuan6;
       this.tuan7 = tuan7;
       this.tuan8 = tuan8;
       this.tuan9 = tuan9;
       this.tuan10 = tuan10;
       this.tuan11 = tuan11;
       this.tuan12 = tuan12;
       this.tuan13 = tuan13;
       this.tuan14 = tuan14;
       this.tuan15 = tuan15;
    }
   
    public SinhvienmonhocId getId() {
        return this.id;
    }
    
    public void setId(SinhvienmonhocId id) {
        this.id = id;
    }
    public Monhoc getMonhoc() {
        return this.monhoc;
    }
    
    public void setMonhoc(Monhoc monhoc) {
        this.monhoc = monhoc;
    }
    public Nguoidung getNguoidung() {
        return this.nguoidung;
    }
    
    public void setNguoidung(Nguoidung nguoidung) {
        this.nguoidung = nguoidung;
    }
    public Boolean getTuan1() {
        return this.tuan1;
    }
    
    public void setTuan1(Boolean tuan1) {
        this.tuan1 = tuan1;
    }
    public Boolean getTuan2() {
        return this.tuan2;
    }
    
    public void setTuan2(Boolean tuan2) {
        this.tuan2 = tuan2;
    }
    public Boolean getTuan3() {
        return this.tuan3;
    }
    
    public void setTuan3(Boolean tuan3) {
        this.tuan3 = tuan3;
    }
    public Boolean getTuan4() {
        return this.tuan4;
    }
    
    public void setTuan4(Boolean tuan4) {
        this.tuan4 = tuan4;
    }
    public Boolean getTuan5() {
        return this.tuan5;
    }
    
    public void setTuan5(Boolean tuan5) {
        this.tuan5 = tuan5;
    }
    public Boolean getTuan6() {
        return this.tuan6;
    }
    
    public void setTuan6(Boolean tuan6) {
        this.tuan6 = tuan6;
    }
    public Boolean getTuan7() {
        return this.tuan7;
    }
    
    public void setTuan7(Boolean tuan7) {
        this.tuan7 = tuan7;
    }
    public Boolean getTuan8() {
        return this.tuan8;
    }
    
    public void setTuan8(Boolean tuan8) {
        this.tuan8 = tuan8;
    }
    public Boolean getTuan9() {
        return this.tuan9;
    }
    
    public void setTuan9(Boolean tuan9) {
        this.tuan9 = tuan9;
    }
    public Boolean getTuan10() {
        return this.tuan10;
    }
    
    public void setTuan10(Boolean tuan10) {
        this.tuan10 = tuan10;
    }
    public Boolean getTuan11() {
        return this.tuan11;
    }
    
    public void setTuan11(Boolean tuan11) {
        this.tuan11 = tuan11;
    }
    public Boolean getTuan12() {
        return this.tuan12;
    }
    
    public void setTuan12(Boolean tuan12) {
        this.tuan12 = tuan12;
    }
    public Boolean getTuan13() {
        return this.tuan13;
    }
    
    public void setTuan13(Boolean tuan13) {
        this.tuan13 = tuan13;
    }
    public Boolean getTuan14() {
        return this.tuan14;
    }
    
    public void setTuan14(Boolean tuan14) {
        this.tuan14 = tuan14;
    }
    public Boolean getTuan15() {
        return this.tuan15;
    }
    
    public void setTuan15(Boolean tuan15) {
        this.tuan15 = tuan15;
    }




}


